core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import (
    DashboardView, 
    AboutView, 
    change_theme, 
    chart_data, 
    login_view, 
    otp_view, 
    logout_view,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', DashboardView.as_view(), name='home'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('otp/', otp_view, name='otp'),
    path('about/', AboutView.as_view(), name='about'),
    path('chart-data/', chart_data, name='data'),
    path('switch/', change_theme, name='change'),
    path('books/', include('books.urls', namespace='books')),
    path('rentals/', include('rentals.urls', namespace='rentals')),
    path("__reload__/", include("django_browser_reload.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Book Rental Administration'
admin.site.index_title = 'Manage the Book Rental System'

rentals/urls.py
from django.urls import path
from .views import (
    search_book_view, 
    BookRentalHistoryView, 
    UpdateRentalStatusView,
    CreateNewRentalView,
    SelectDownloadRentalsView
)

app_name = 'rentals'

urlpatterns = [
    path('', search_book_view, name='main'),
    path('<str:book_id>/', BookRentalHistoryView.as_view(), name="detail"),
    path('<str:book_id>/new/', CreateNewRentalView.as_view(), name="new"),
    path('<str:book_id>/download/', SelectDownloadRentalsView.as_view(), name="download"),
    path('<str:book_id>/<pk>/', UpdateRentalStatusView.as_view(), name="update"),
]

rentals/models.py
from django.db import models
from books.models import Book
from customers.models import Customer
from datetime import timedelta
from .choices import STATUS_CHOICES
# Create your models here.

class Rental(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    status = models.CharField(max_length=2, choices=STATUS_CHOICES)
    rent_start_date = models.DateField(help_text='when the book was rented')
    rent_end_date = models.DateField(help_text='deadline', blank=True)
    return_date = models.DateField(blank=True, null=True, help_text='actual return date')
    is_closed = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.book.isbn} rented by {self.customer.username}"
    
    @property
    def status_text(self):
        statuses = dict(STATUS_CHOICES)
        return statuses[self.status]
    
    def save(self, *args, **kwargs):
        if not self.rent_end_date:
            self.rent_end_date = self.rent_start_date + timedelta(days=14)
        super().save(*args, **kwargs)

    class Meta:
        ordering = ('-created',)

rentals/forms.py
from django import forms 
from .choices import FORMAT_CHOICES


class SearchBookForm(forms.Form):
    search = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder': 'search by book id ...'}))


class SelectExportOptionForm(forms.Form):
    format = forms.ChoiceField(choices=FORMAT_CHOICES, widget=forms.RadioSelect())

rentals/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from .forms import SearchBookForm, SelectExportOptionForm
from books.models import Book
from django.views.generic import ListView, UpdateView, CreateView, FormView
from .models import Rental
from django.db.models import Q
from datetime import datetime
from django.contrib import messages
from .choices import FORMAT_CHOICES
from .admin import RentalResource
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required
def search_book_view(request):
    form = SearchBookForm(request.POST or None)
    search_query = request.POST.get('search', None)
    book_ex = Book.objects.filter(Q(isbn=search_query) | Q(id=search_query)).exists()

    if search_query is not None and book_ex:
        return redirect('rentals:detail', search_query)

    context = {
        'form': form,
    }
    return render(request, 'rentals/main.html', context)


class BookRentalHistoryView(LoginRequiredMixin, ListView):
    model = Rental # Rental.objects.all()
    template_name = 'rentals/detail.html'

    def get_queryset(self):
        book_id = self.kwargs.get('book_id')
        return Rental.objects.filter(Q(book__isbn=book_id) | Q(book__id=book_id))
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        book_id = self.kwargs.get('book_id')
        obj = Book.objects.filter(Q(isbn=book_id) | Q(id=book_id)).first()
        # obj = get_object_or_404(Book, Q(isbn=book_id) | Q(id=book_id))
        context['object'] = obj
        context['book_id'] = book_id
        return context
    

class UpdateRentalStatusView(LoginRequiredMixin, UpdateView):
    model = Rental
    template_name = 'rentals/update.html'
    fields = ("status",)

    def get_success_url(self):
        book_id = self.kwargs.get('book_id')
        return reverse('rentals:detail', kwargs={'book_id':book_id})
    
    def form_valid(self, form):
        instance = form.save(commit=False)
        if instance.status == '#1':
            instance.return_date = datetime.today().date()
            instance.is_closed = True
        instance.save()
        messages.add_message(self.request, messages.INFO, f"{instance.book.id} was successfuly updated")
        return super().form_valid(form)
    

class CreateNewRentalView(LoginRequiredMixin, CreateView):
    model = Rental
    template_name = 'rentals/new.html'
    fields = ('customer',)

    def get_success_url(self):
        book_id = self.kwargs.get('book_id')
        return reverse('rentals:detail', kwargs={'book_id':book_id})
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["book_id"] = self.kwargs.get('book_id')
        return context
    
    def form_valid(self, form):
        instance = form.save(commit=False)
        book_id = self.kwargs.get('book_id')
        obj = Book.objects.get(id=book_id)
        instance.book = obj
        instance.status = '#0'
        instance.rent_start_date = datetime.today().date()
        instance.save()
        return super().form_valid(form)
    

class SelectDownloadRentalsView(LoginRequiredMixin, FormView):
    template_name = 'rentals/select_format.html'
    form_class = SelectExportOptionForm

    def get_success_url(self):
        return self.request.path
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        book_id = self.kwargs.get('book_id')
        context['book_id'] = book_id
        return context
    
    def post(self, request, **kwargs):
        formats = dict(FORMAT_CHOICES)
        format = self.request.POST.get('format')
        format = formats[format]

        book_id = self.kwargs.get('book_id')
        qs = Rental.objects.filter(Q(book__isbn=book_id) | Q(book__id=book_id))
        dataset = RentalResource().export(qs)

        if format == 'csv':
            ds = dataset.csv
        elif format == 'xls':
            ds = dataset.xls
        else:
            ds = dataset.json
        response = HttpResponse(ds, content_type=format)
        response['Content-Disposition'] = f'attachment; filename=rentals.{format}'
        return response

rentals/templates/rentals/detail.html
{% extends 'base.html' %}
{% load get_status_text %}

{% block title %}
rental history
{% endblock title %}


{% block content %}

{% if messages %}
    {% for message in messages %}
        {% if 'info' in message.tags %}
            {% include 'components/alert.html' with is_info=True title="Success" body=message %}
        {% endif %}
    {% endfor %}
{% endif %}


{% include 'components/header.html' with title=object.title.title description=object.title.publisher.name %}

{% if object %}
    {% if object_list %}
    <div class="overflow-x-auto"> 
        <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
            <thead class="text-xs text-gray-700 uppercase dark:bg-gray-700 dark:text-gray-400">
                <tr class="border">
                    <th scope="col" class="py-3 px-6">
                        #
                    </th>
                    <th scope="col" class="py-3 px-6">
                        customer
                    </th>
                    <th scope="col" class="py-3 px-6">
                        id
                    </th>
                    <th scope="col" class="py-3 px-6">
                        isbn
                    </th>
                    <th scope="col" class="py-3 px-6">
                        status
                    </th>
                    <th scope="col" class="py-3 px-6">
                        start
                    </th>
                    <th scope="col" class="py-3 px-6">
                        end
                    </th>
                    <th scope="col" class="py-3 px-6">
                        return
                    </th>
                    <th scope="col" class="py-3 px-6">
                        is closed
                    </th>
                    
                </tr>
            </thead>
            <tbody>
                {% for obj in object_list %}
                <tr class="border-b dark:bg-gray-800 dark:border-gray-700">
                    <td scope="row" class="py-4 px-6 font-medium text-gray-900 dark:text-white">
                        {{forloop.counter}}
                    </td>
                    <td class="py-4 px-6">
                        {{obj.customer.username}}
                    </td>
                    <td class="py-4 px-6">
                        {{obj.book.id}}
                    </td>
                    <td class="py-4 px-6">
                        {{obj.book.isbn}}
                    </td>
                    <td class="py-4 px-6">
                        {{obj.status|get_status_text}}
                    </td>
                    <td class="py-4 px-6">
                        {{obj.rent_start_date}}
                    </td>
                    <td class="py-4 px-6">
                        {{obj.rent_end_date}}
                    </td>
                    <td class="py-4 px-6">
                        {% if obj.return_date %}{{obj.return_date}}{% else %}-{% endif %}
                    </td>
                    <td class="py-4 px-6">
                        {% if obj.is_closed %}
                            <i class="fa-solid fa-check fa-lg text-teal-300"></i>
                        {% else %}
                            <i class="fa-solid fa-xmark fa-lg text-red-500"></i>
                        {% endif %}

                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="mt-6 h-12">
            <a href="{% url 'rentals:download' book_id %}" class="p-3 bg-rose-400 hover:bg-rose-500 text-white rounded-lg">download</a>
        </div>
    {% else %}
        no rental data
    {% endif %}
{% else %}
    no book found
{% endif %}

{% endblock content %}

rentals/templates/rentals/main.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load static %}

{% block scripts %}
    <script src="{% static 'rentals/main.js' %}" defer></script>
{% endblock scripts %}

{% block title %}
search rentals
{% endblock title %}

{% block content %}

<div class="flex justify-center items-center h-[500px]">
    <form class="w-[400px]" id="search-form" method="POST" autocomplete="off">
        {% csrf_token %}
        <label for="{{ form.search.id_for_label }}" class="block text-center text-3xl text-gray-700 dark:text-white font-bold mb-2">search for books</label>
        {{ form.search|add_class:'bg-slate-100 dark:bg-slate-300 text-slate-800 rounded-lg p-3 drop-shadow-xl w-full' }}
    </form>
</div>

{% endblock content %}

rentals/templates/rentals/new.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}new{% endblock title %}

{% block content %}
{% include 'components/header.html' with title="Add new rental" description=book_id is_go_back=True %}
<form method="POST" class="w-1/2">
    {% csrf_token %}
    <div class="mb-2">
        <label for="{{ form.customer.id_for_label }}" class="block font-bold text-slate-800 dark:text-slate-300">Customer:</label>
        {{ form.customer|add_class:'bg-slate-100 dark:bg-slate-300 text-slate-800 rounded p-2 w-full' }} 
    </div>
    <button type="submit" class="p-3 bg-sky-500 hover:bg-sky-600 rounded-lg text-white">rent</button>
</form>
{% endblock content %}

rentals/templates/rentals/select_format.html
{% extends 'base.html' %}

{% block title %}download rentals{% endblock title %}

{% block content %}

{% include 'components/header.html' with title="Download data" description=book_id is_go_back=True %}


<form method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit" class="p-3 mt-3 bg-sky-500 hover:bg-sky-600 rounded-lg text-white">download</button>
</form>


{% endblock content %}

rentals/templates/rentals/update.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
update status
{% endblock title %}

{% block content %}

{% if messages %}
    {% for message in messages %}
        {% if 'info' in message.tags %}
            {% include 'components/alert.html' with is_info=True title="Success" body=message %}
        {% endif %}
    {% endfor %}
{% endif %}

{% include 'components/header.html' with title="Update rental status" description=object.book.id is_go_back=True %}

{% if object.is_closed %}
    The rental status is closed
{% else %}
    <form method="POST" class="w-1/2">
        {% csrf_token %}
        <div class="mb-2">
            <label for="{{ form.status.id_for_label }}" class="block font-bold text-slate-800 dark:text-slate-300">status:</label>
            {{ form.status|add_class:'bg-slate-100 dark:bg-slate-300 text-slate-800 rounded p-2 w-full' }} 
        </div>
        <button type="submit" class="px-3 py-2 text-white bg-sky-500 hover:bg-sky-600 rounded-xl mt-3">
            update
        </button>
    </form>
{% endif %}


{% endblock content %}