books/urls.py
from django.urls import path
from .views import (
    BookTitleListView, 
    BookTitleDetailView,
    BookDetailView,
    BookDeleteView
)

app_name = 'books'

urlpatterns = [
    path('', BookTitleListView.as_view(), {'letter': None}, name='main'),
    path('<str:letter>/', BookTitleListView.as_view(), name='main'),
    path('<str:letter>/<slug>/', BookTitleDetailView.as_view(), name='detail'),
    path('<str:letter>/<slug>/<str:book_id>/', BookDetailView.as_view(), name='detail-book'),
    path('<str:letter>/<slug>/<str:book_id>/delete/', BookDeleteView.as_view(), name='delete-book'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import (
    DashboardView, 
    AboutView, 
    change_theme, 
    chart_data, 
    login_view, 
    otp_view, 
    logout_view,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', DashboardView.as_view(), name='home'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('otp/', otp_view, name='otp'),
    path('about/', AboutView.as_view(), name='about'),
    path('chart-data/', chart_data, name='data'),
    path('switch/', change_theme, name='change'),
    path('books/', include('books.urls', namespace='books')),
    path('rentals/', include('rentals.urls', namespace='rentals')),
    path("__reload__/", include("django_browser_reload.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Book Rental Administration'
admin.site.index_title = 'Manage the Book Rental System'

rentals/urls.py
from django.urls import path
from .views import (
    search_book_view, 
    BookRentalHistoryView, 
    UpdateRentalStatusView,
    CreateNewRentalView,
    SelectDownloadRentalsView
)

app_name = 'rentals'

urlpatterns = [
    path('', search_book_view, name='main'),
    path('<str:book_id>/', BookRentalHistoryView.as_view(), name="detail"),
    path('<str:book_id>/new/', CreateNewRentalView.as_view(), name="new"),
    path('<str:book_id>/download/', SelectDownloadRentalsView.as_view(), name="download"),
    path('<str:book_id>/<pk>/', UpdateRentalStatusView.as_view(), name="update"),
]

books/models.py
from django.db import models
from publishers.models import Publisher
from authors.models import Author
from django.utils.text import slugify
import uuid
from django.urls import reverse
# imports for qrcode generation
import qrcode
from io import BytesIO
from django.core.files import File
from PIL import Image
from rentals.choices import STATUS_CHOICES
from .utils import hash_book_info
# Create your models here.

class BookTitle(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(blank=True)
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    @property
    def books(self):
        return self.book_set.all()
    
    def get_absolute_url(self):
        letter = self.title[:1].lower()
        return reverse("books:detail", kwargs={"letter": letter, "slug": self.slug})
    
    def __str__(self):
        return f"Book position: {self.title}"
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)


class Book(models.Model):
    """
    curent status for books
    id: 1,2,3 ...
    isbn: unique 24 character long string

    future state
    id: 36 character long string
    isbn: hashed string based on book title & publisher name
    many BOOKS can have the SAME ISBN
    """
    id = models.CharField(primary_key=True, max_length=36, default=uuid.uuid4, editable=False)
    title = models.ForeignKey(BookTitle, on_delete=models.CASCADE)
    isbn = models.CharField(max_length=24, blank=True)
    qr_code = models.ImageField(upload_to='qr_codes', blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        letter = self.title.title[:1].lower()
        return reverse("books:detail-book", kwargs={"letter": letter, "slug": self.title.slug, "book_id": self.id})
    
    def delete_object(self):
        letter = self.title.title[:1].lower()
        return reverse('books:delete-book', kwargs={'letter':letter, 'slug': self.title.slug, "book_id": self.id})

    def __str__(self):
        return str(self.title)
    
    @property
    def status(self):
        if len(self.rental_set.all()) > 0:
            statuses = dict(STATUS_CHOICES)
            return statuses[self.rental_set.first().status]
        return False
    
    @property
    def rental_id(self):
        if len(self.rental_set.all()) > 0:
            return self.rental_set.first().id
        return None
    
    @property
    def is_available(self):
        if len(self.rental_set.all()) > 0:
            status = self.rental_set.first().status
            return True if status == '#1' else False
        return True

    def save(self, *args, **kwargs):
        if not self.isbn:
            # self.isbn = str(uuid.uuid4()).replace('-', '')[:24].lower()
            self.isbn = hash_book_info(self.title.title, self.title.publisher.name)

            # generate qr code
            qrcode_img = qrcode.make(self.isbn)
            canvas = Image.new('RGB', (qrcode_img.pixel_size, qrcode_img.pixel_size), 'white')
            canvas.paste(qrcode_img)
            fname = f'qr_code-{self.isbn}.png'
            buffer = BytesIO()
            canvas.save(buffer, 'PNG')
            self.qr_code.save(fname, File(buffer), save=False)
            canvas.close()

        super().save(*args, **kwargs)

books/forms.py
from django import forms 
from .models import BookTitle
from django.core.exceptions import ValidationError

class BookTitleForm(forms.ModelForm):
    class Meta:
        model = BookTitle
        fields = ('publisher', 'author', 'title')
        # widgets = {
        #     'title': forms.TextInput(attrs={'class': 'border bg-purple-200 rounded-xl p-3'}),
        #     'author': forms.Select(attrs={'class': 'border bg-purple-200 rounded-xl p-3'}),
        #     'publisher': forms.Select(attrs={'class': 'border bg-purple-200 rounded-xl p-3'})
        # }

    def clean(self):
        title = self.cleaned_data.get('title')

        if len(title) < 5:
            error_msg = 'the title is too short'
            self.add_error('title', error_msg)
            # raise ValidationError(error_msg)
        
        book_tile_exists = BookTitle.objects.filter(title__iexact=title).exists()

        if book_tile_exists:
            self.add_error('title', 'this book title already exists')

        return self.cleaned_data

books/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import BookTitle, Book
from django.views.generic import (
    ListView, 
    FormView,
    DetailView,
    DeleteView
)
from .forms import BookTitleForm
from django.urls import reverse, reverse_lazy
from django.contrib import messages
import string
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

class BookTitleListView(LoginRequiredMixin, FormView, ListView):
    # model = BookTitle
    # queryset = BookTitle.objects.all()
    template_name = 'books/main.html'
    context_object_name = 'qs'
    form_class = BookTitleForm
    # success_url = reverse_lazy('books:main')
    # ordering = ('-created',)
    # model_list.html -> booktitle_list.html
    # object_list
    i_instance = None

    def get_success_url(self):
        return self.request.path

    def get_queryset(self):
        parameter = self.kwargs.get('letter') if self.kwargs.get('letter') else 'a'
        return BookTitle.objects.filter(title__startswith=parameter)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        letters = list(string.ascii_uppercase)
        context['letters'] = letters
        context['selected_letter'] = self.kwargs.get('letter') if self.kwargs.get('letter') else 'a'
        return context
    
    def form_valid(self, form):
        self.i_instance = form.save()
        messages.add_message(self.request, messages.INFO, f"Book title: {self.i_instance.title} has been created")
        return super().form_valid(form)
    
    def form_invalid(self, form):
        print(form.errors)
        self.object_list = self.get_queryset()
        messages.add_message(self.request, messages.ERROR, form.errors)
        return super().form_invalid(form)

# def book_title_list_view(request):
#     qs = BookTitle.objects.all()
#     return render(request, 'books/main.html', {'qs':qs})

# OPTION 1 - BOOK LIST VIEW + overriding get_queryset method
# class BookListView(ListView):
#     template_name = 'books/detail.html'
#     paginate_by = 2

#     def get_queryset(self):
#         title_slug = self.kwargs.get('slug')
#         return Book.objects.filter(title__slug=title_slug)

# OPTION 2 - BOOK TITLE DETAIL VIEW + model method
class BookTitleDetailView(LoginRequiredMixin, DetailView):
    model = BookTitle
    template_name = 'books/detail.html'


# def book_title_detail_view(request, **kwargs):
#     slug = kwargs.get('slug')
#     obj = BookTitle.objects.get(slug=slug)
#     return render(request, 'books/detail.html', {'obj': obj})

class BookDetailView(LoginRequiredMixin, DetailView):
    model = Book
    template_name = 'books/detail_book.html'

    def get_object(self):
        id = self.kwargs.get('book_id')
        # obj = Book.objects.get(isbn=id)
        obj = get_object_or_404(Book, id=id)
        return obj
    

class BookDeleteView(LoginRequiredMixin, DeleteView):
    model = Book
    template_name = 'books/confirm_delete.html'

    def get_object(self):
        id = self.kwargs.get('book_id')
        obj = get_object_or_404(Book, id=id)
        return obj
    
    def get_success_url(self):
        messages.add_message(self.request, messages.INFO, f"The book with isbn {self.get_object().isbn} has been deleted")
        letter = self.kwargs.get('letter')
        slug = self.kwargs.get('slug')
        return reverse('books:detail', kwargs={'letter':letter, 'slug':slug})

books/templates/books/confirm_delete.html
{% extends 'base.html' %}

{% block title %}delete book?{% endblock title %}

{% block content %}
<div class="w-full bg-white dark:bg-slate-700 shadow p-3 rounded">
    <h1 class="text-2xl  mb-4">Are you sure you want to delete <span class="font-semibold">{{object.isbn}}</span> ?</h1>
    <div class="mb-4">Deleteing this item is permanent and cannot be undone!</div>
    <form method="POST">
        {% csrf_token %}
        <button type="submit" class="bg-red-500 hover:bg-red-600 text-white font-bold rounded py-2 px-4">delete</button>
    </form>
</div>
{% endblock content %}

books/templates/books/detail.html
{% extends 'base.html' %}

{% block title %}book title detail{% endblock title %}

{% block content %}

{% if messages %}
    {% for message in messages %}
        {% if 'info' in message.tags %}
            {% include 'components/alert.html' with is_info=True title="Success" body=message %}
        {% endif %}
    {% endfor %}
{% endif %}

{% include 'components/header.html' with title=object.title description='book title details' is_go_back=True %}

<div class="overflow-x-auto">
    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase dark:bg-gray-700 dark:text-gray-400">
            <tr class="border">
                <th scope="col" class="py-3 px-6">
                    #
                </th>
                <th scope="col" class="py-3 px-6">
                    title
                </th>
                <th scope="col" class="py-3 px-6">
                    book id
                </th>
                <th scope="col" class="py-3 px-6">
                    isbn
                </th>
                <th scope="col" class="py-3 px-6">
                    qr code
                </th>
                <th scope="col" class="py-3 px-6">
                    status
                </th>
                <th scope="col" class="py-3 px-6">
                    available
                </th>
                <th scope="col" class="py-3 px-6">
                    select
                </th>
                <th scope="col" class="py-3 px-6">
                    delete
                </th>
            </tr>
        </thead>
        <tbody>
            {% for obj in object.books %}
            <tr class="border-b dark:bg-gray-800 dark:border-gray-700 {% if not obj.is_read  %}font-bold{% endif %}">
                <td scope="row" class="py-4 px-6 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                    {{forloop.counter}}
                </td>
                <td class="py-4 px-6">
                    {{obj.title.title}}
                </td>
                <td class="py-4 px-6">
                    {{obj.id}}
                </td>
                <td class="py-4 px-6">
                    {{obj.isbn}}
                </td>
                <td class="py-4 px-6">
                    <img src="{{obj.qr_code.url}}" alt="{{obj.isbn}}" class="h-12 w-12 rounded">
                </td>
                <td class="py-4 px-6">
                    {% if obj.status %}{{obj.status}}{% else %}never rented{% endif %}
                </td>
                <td class="py-4 px-6">
                    {% if obj.is_available %}
                        <i class="fa-solid fa-check text-green-500"></i>
                    {% else %}
                        <i class="fa-solid fa-xmark text-red-500"></i>
                    {% endif %}
                </td>
                <td class="py-4 px-6">
                    {% include 'components/buttons/select_button.html' with href=obj.get_absolute_url %}
                </td>
                <td class="py-4 px-6">
                    {% include 'components/buttons/delete_button.html' with href=obj.delete_object %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% comment %} {% if is_paginated %}
    <div class="mt-3">
        <ul class="inline-flex items-center -space-x-px">

            {% if page_obj.has_previous %}
                <li>
                    <a {% if page_obj.has_previous %}href="?page={{ page_obj.previous_page_number }}"{% else %} href="" {% endif %} class="block px-3 py-2 leading-tight text-gray-500 bg-white border border-gray-300 rounded-l-lg hover:bg-gray-200 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">                    
                        <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clip-rule="evenodd"></path></svg>
                    </a>
                </li>
            {% endif %}

            {% for i in page_obj.paginator.page_range %}
                {% if page_obj.number == i %}
                    <li><a class="px-3 py-2 leading-tight text-gray-500 dark:text-gray-100 bg-gray-200 dark:bg-gray-700 border border-gray-300 hover:bg-white hover:text-gray-700  dark:border-gray-700 dark:hover:bg-gray-700 dark:hover:text-white" href="?page={{ i }}">{{ i }}</a></li>
                {% else %}
                    <li><a class="px-3 py-2 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li>
                    <a {% if page_obj.has_next %}href="?page={{ page_obj.next_page_number }}"{% else %} href="" {% endif %} class="block px-3 py-2 leading-tight text-gray-500 bg-white border border-gray-300 rounded-r-lg hover:bg-gray-200 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">                    
                        <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"></path></svg>
                    </a>
                </li>
            {% endif %}
        </ul>
    </div>
{% endif %}  {% endcomment %}

{% endblock content %}

books/templates/books/detail_book.html
{% extends 'base.html' %}
{% load static %}

{% block scripts %}
    <script src="{% static 'books/detail_book.js' %}" defer></script>
{% endblock scripts %}

{% block title %}book detail{% endblock title %}


{% block content %}
{% include 'components/header.html' with title=object.title.title description=object.title.publisher.name is_go_back=True %}

<div class="flex justify-center">
    <div>
        <div class="text-center mb-3">
            {% if object.is_available %}
                <a href="{% url 'rentals:new' object.id %}" class="p-3 bg-sky-500 hover:bg-sky-600 rounded-lg text-white">rent</a>
                {% if object.status %}
                    {{object.status}}
                {% else %}
                    never rented
                {% endif %}
            {% else %}
                not available
            {% endif %}
        </div>
        <img src="{{object.qr_code.url}}" alt="{{object.isbn}}" class="w-52 h-52 rounded-lg" >
        <div class="mt-7 text-center">
            {% if not object.is_available %}
                <a href="{% url 'rentals:update' object.id object.rental_id %}" class="bg-yellow-500 hover:bg-yellow-600 text-white dark:text-slate-900 rounded p-3">change status</a>
            {% endif %}
            <a href="{% url 'rentals:detail' object.id %}" class="bg-rose-500 hover:bg-rose-600 rounded p-3 text-white">history</a>
        </div>
    </div>  
</div>

<div class="flex justify-center">
    <div class="mt-10 p-3 rounded-lg relative bg-slate-200 dark:bg-slate-600 border border-slate-300 dark:border-slate-600 text-slate-700 dark:text-slate-200 drop-shadow-md w-1/2">
        <div id="book-id-box">{{object.id}}</div>
        <div class="dark:text-white absolute right-3 top-3" id="copy-btn-box">
            <i class="fa-regular fa-copy fa-xl cursor-pointer"></i>
        </div>
</div>


{% endblock content %}

books/templates/books/main.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block scripts %}
    <script src="{% static 'books/main.js' %}" defer></script>
    <script src="{% static 'js/form_modal.js' %}" defer></script>
{% endblock scripts %}

{% block title %}book title list{% endblock title %}

{% block content %}
    {% comment %} {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
            <div class="font-bold text-xl text-red-400">{{ error }}</div>
        {% endfor %}
    {% endif %} {% endcomment %}

    {% if messages %}
        {% for message in messages %}
            {% if 'info' in message.tags %}
                {% include 'components/alert.html' with is_info=True title="Success" body=message %}
            {% elif 'error' in message.tags %}
                {% include 'components/alert.html' with is_info=False title="Error" body=message %}
            {% endif %}
        {% endfor %}
    {% endif %}

    <!-- form modal -->
    <div class="hidden relative z-50" aria-labelledby="modal-title" role="dialog" aria-modal="true" id="form-modal">
        <div class="fixed inset-0 bg-gray-500 bg-opacity-75"></div>
        <div class="fixed inset-0 z-10 overflow-y-auto">
            <div class="flex min-h-full items-center justify-center p-4 text-center" id="backdrop">
                <div class="relative transform overflow-hidden rounded-lg text-left shadow-xl transition-all my-8">
                    <form action="" method="POST">
                        {% csrf_token %}
                        <div class="bg-white dark:text-white dark:bg-slate-300 pt-5 pb-4 px-8">
                            <div class="mt-3 text-left">
                                <h3 class="text-2xl font-medium leading-6 text-gray-900" id="modal-title">
                                    add new book title
                                </h3>
                                <div class="mt-3">                            
                                    <div class="mb-2">
                                        <label for="{{ form.title.id_for_label }}" class="block font-bold text-slate-800 dark:text-slate-300">title:</label>
                                        {{ form.title|add_class:'bg-slate-100 dark:bg-slate-300 text-slate-800 rounded p-2 w-full' }} 
                                        {% if form.title.errors %}
                                            {% for error in form.title.errors  %}
                                                <div class="my-1 text-red-500 font-bold text-sm">{{ error }}</div>
                                            {% endfor %}
                                        {% endif %}
                                    </div>
                            
                                    <div class="mb-2">
                                        <label for="{{ form.author.id_for_label }}" class="block font-bold text-slate-800 dark:text-slate-300">author:</label>
                                        {{ form.author|add_class:'bg-slate-100 dark:bg-slate-300 text-slate-800 rounded p-2 w-full' }} 
                                    </div>
                            
                                    <div class="mb-2">
                                        <label for="{{ form.publisher.id_for_label }}" class="block font-bold text-slate-800 dark:text-slate-300">publisher:</label>
                                        {{ form.publisher|add_class:'bg-slate-100 dark:bg-slate-300 text-slate-800 rounded p-2 w-full' }} 
                                    </div>  
                                </div>
                            </div>
                        </div>
                        <div class="bg-gray-50 dark:text-white dark:bg-slate-400 px-4 py-3 sm:flex sm:flex-row-reverse sm:px-6">
        
                            <button type="submit" class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded">
                                save
                            </button>

                            <button type="button" id="cancel-btn" class="bg-red-500 hover:bg-red-600 text-white font-semibold py-2 px-4 border border-red-600 rounded mr-3">
                                cancel
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    {% include 'components/header.html' with title="Book titles" description="List of all the book titles available" is_form_available=True icon="<i class='fa-solid fa-plus'></i>" %}

    {% for letter in letters %}
        <a href="{% url 'books:main' letter|lower %}" class="{% if letter == selected_letter|upper%}underline{% endif %}">{{ letter }}</a>
    {% endfor %}

    {% if qs %}
        <ul>
            {% for el in qs %}
                <li><a href="{{el.get_absolute_url}}">{{el.title}}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <div>no book titles staring with <b>{{selected_letter}}</b></div>
    {% endif %}

{% endblock content %}