books/urls.py
from django.urls import path
from .views import (
    BookTitleListView, 
    BookTitleDetailView,
    BookDetailView,
    BookDeleteView
)

app_name = 'books'

urlpatterns = [
    path('', BookTitleListView.as_view(), {'letter': None}, name='main'),
    path('<str:letter>/', BookTitleListView.as_view(), name='main'),
    path('<str:letter>/<slug>/', BookTitleDetailView.as_view(), name='detail'),
    path('<str:letter>/<slug>/<str:book_id>/', BookDetailView.as_view(), name='detail-book'),
    path('<str:letter>/<slug>/<str:book_id>/delete/', BookDeleteView.as_view(), name='delete-book'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import (
    DashboardView, 
    AboutView, 
    change_theme, 
    chart_data, 
    login_view, 
    otp_view, 
    logout_view,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', DashboardView.as_view(), name='home'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('otp/', otp_view, name='otp'),
    path('about/', AboutView.as_view(), name='about'),
    path('chart-data/', chart_data, name='data'),
    path('switch/', change_theme, name='change'),
    path('books/', include('books.urls', namespace='books')),
    path('rentals/', include('rentals.urls', namespace='rentals')),
    path("__reload__/", include("django_browser_reload.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Book Rental Administration'
admin.site.index_title = 'Manage the Book Rental System'

templates/layout/navbar.html
{% load static %}
<nav class="fixed flex items-center h-16 bg-gradient-to-r from-cyan-500 to-blue-700 mb-2 w-full z-10 text-white">
    <div class="flex justify-between items-center w-full px-4 py-3">
        <div>
            <a href="{% url 'home' %}"><img src="{% static 'images/logo.png' %}" class="h-12" alt="book rent logo"></a>
        </div>
        {% if request.user.is_authenticated %}
        <div class="flex items-center">
            <div class="relative" id="dropdown-box">
                <button id="btn-dropdown" class="bg-white bg-opacity-10 rounded drop-shadow-lg p-3 hover:opacity-80 focus:ring-4 focus:ring-blue-300" type="button">menu &nbsp; <i class="fa-solid fa-caret-down"></i></button>

                <div id="dropdown" class="hidden absolute right-0 bg-white shadow min-w-full rounded">
                    <ul class="py-1 text-sm text-slate-700">
                        <li>
                            <div class="block py-2 px-4 border-b border-slate-200">{{request.user.username}}</div>
                        </li>
                        <li>
                            <a href="{% url 'logout' %}" class="block py-2 px-4 hover:bg-gray-100">logout</a>
                        </li>
                    </ul>

                </div>
            </div>

            <div class="bg-white rounded-full ml-3">
                <svg width="55" height="55" data-jdenticon-value="{{request.user.username}}"></svg>
            </div>
        </div>
        {% endif %}
    </div>
</nav>

templates/layout/sidebar.html
{% url 'home' as path_to_home %}
{% url 'about' as path_to_about %}
{% url 'books:main' as path_to_books %}
{% url 'rentals:main' as path_to_rentals %}

<aside class="hidden md:block sticky bg-slate-900 h-screen text-white w-full pt-24 text-sm">
    <ul>
        <li class="mb-6 mx-auto">
            <a href="{{path_to_home}}" class="grid h-12 place-items-center cursor-pointer hover:text-slate-200 duration-300 text-slate-500 {% if request.path == path_to_home %}text-white{% endif %}">
                <i class="fa-solid fa-chart-pie fa-xl"></i>
                <p>dashboard</p>
            </a>
        </li>
        <li class="mb-6 mx-auto">
            <a href="{{path_to_books}}" class="grid h-12 place-items-center cursor-pointer hover:text-slate-200 duration-300 text-slate-500 {% if 'books' == request.resolver_match.view_name|slice:'0:5' %}text-white{% endif %}">
                <i class="fa-solid fa-book fa-xl"></i>
                <p>books</p>
            </a>
        </li>
        <li class="mb-6 mx-auto">
            <a href="{{path_to_rentals}}" class="grid h-12 place-items-center cursor-pointer hover:text-slate-200 duration-300 text-slate-500 {% if 'rentals' == request.resolver_match.view_name|slice:'0:7'%}text-white{% endif %}">
                <i class="fa-solid fa-bookmark fa-xl"></i>
                <p>rentals</p>
            </a>
        </li>
        <li class="mb-6 mx-auto">
            <a href="{{path_to_about}}" class="grid h-12 place-items-center cursor-pointer hover:text-slate-200 duration-300 text-slate-500 {% if request.path == path_to_about %}text-white{% endif %}">
                <i class="fa-solid fa-circle-question fa-xl"></i>
                <p>about</p>
            </a>
        </li>
    </ul>
</aside>